# OS: Ubuntu 22+
name: py3.11-cuda11.8-PyTorch-IS # Environment's name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
prefix:
    - ~/miniconda3/envs/py3.11-cuda11.8-PyTorch-IS

#conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
#pip install IPython scipy 